/**
 * @seashore/tool - Types
 *
 * Type definitions for tools
 */

import type { z, ZodSchema } from 'zod';

/**
 * Tool execution context
 */
export interface ToolContext {
  /** Unique execution ID */
  readonly executionId: string;

  /** Thread ID if within an agent conversation */
  readonly threadId?: string;

  /** User ID if available */
  readonly userId?: string;

  /** Abort signal for cancellation */
  readonly signal?: AbortSignal;

  /** Custom metadata */
  readonly metadata?: Record<string, unknown>;
}

/**
 * Tool execution result
 */
export interface ToolResult<T> {
  /** Whether execution succeeded */
  readonly success: boolean;

  /** Result data (if successful) */
  readonly data?: T;

  /** Error message (if failed) */
  readonly error?: string;

  /** Execution duration in milliseconds */
  readonly durationMs: number;

  /** Additional metadata */
  readonly metadata?: Record<string, unknown>;
}

/**
 * Tool configuration
 */
export interface ToolConfig<TInput extends ZodSchema, TOutput> {
  /** Tool name (unique identifier) */
  readonly name: string;

  /** Tool description (LLM uses this to decide when to call) */
  readonly description: string;

  /** Input parameter schema (Zod) */
  readonly inputSchema: TInput;

  /** Execution function */
  readonly execute: (input: z.infer<TInput>, context: ToolContext) => Promise<TOutput>;

  /** Whether user approval is required */
  readonly needsApproval?: boolean;

  /** Execution timeout in milliseconds */
  readonly timeout?: number;

  /** Retry configuration */
  readonly retry?: RetryConfig;
}

/**
 * Retry configuration
 */
export interface RetryConfig {
  /** Maximum retry attempts */
  readonly maxAttempts: number;

  /** Delay between retries in milliseconds */
  readonly delay: number;

  /** Backoff multiplier (default: 2) */
  readonly backoffMultiplier?: number;
}

/**
 * Tool interface
 */
export interface Tool<TInput, TOutput> {
  /** Tool name */
  readonly name: string;

  /** Tool description */
  readonly description: string;

  /** JSON Schema for LLM function calling */
  readonly jsonSchema: JsonSchema;

  /** Whether user approval is required */
  readonly needsApproval: boolean;

  /** Execute the tool */
  execute(input: TInput, context?: Partial<ToolContext>): Promise<ToolResult<TOutput>>;

  /** Validate input */
  validate(input: unknown): input is TInput;

  /** Parse and validate input (throws on invalid) */
  parse(input: unknown): TInput;
}

/**
 * JSON Schema type enumeration
 */
export type JsonSchemaType =
  | 'object'
  | 'array'
  | 'string'
  | 'number'
  | 'integer'
  | 'boolean'
  | 'null';

/**
 * JSON Schema representation
 *
 * Supports all standard JSON Schema properties generated by Zod 4's toJSONSchema()
 */
export interface JsonSchema {
  /** JSON Schema version identifier */
  readonly $schema?: string;

  /** Type (supports multiple JSON Schema types) */
  readonly type?: JsonSchemaType;

  /** Object property definitions */
  readonly properties?: Record<string, JsonSchemaProperty>;

  /** Required field list */
  readonly required?: readonly string[];

  /** Whether additional properties are allowed */
  readonly additionalProperties?: boolean;

  /** Array item type */
  readonly items?: JsonSchemaProperty;

  /** Enum values list */
  readonly enum?: readonly unknown[];

  /** Constant value (literal types) */
  readonly const?: unknown;

  /** Union type (oneOf) */
  readonly oneOf?: readonly JsonSchemaProperty[];

  /** Union type (anyOf) */
  readonly anyOf?: readonly JsonSchemaProperty[];

  /** Numeric constraints */
  readonly minimum?: number;
  readonly maximum?: number;

  /** String constraints */
  readonly minLength?: number;
  readonly maxLength?: number;

  /** Array constraints */
  readonly minItems?: number;
  readonly maxItems?: number;

  /** String format (uuid, email, uri, etc.) */
  readonly format?: string;

  /** Default value */
  readonly default?: unknown;

  /** Description */
  readonly description?: string;
}

/**
 * JSON Schema property definition
 *
 * Supports nested objects, arrays, union types, and other complex structures
 */
export interface JsonSchemaProperty {
  /** Type */
  readonly type?: string;

  /** Description */
  readonly description?: string;

  /** Enum values list */
  readonly enum?: readonly unknown[];

  /** Constant value (literal types) */
  readonly const?: unknown;

  /** Array item type */
  readonly items?: JsonSchemaProperty;

  /** Nested object properties */
  readonly properties?: Record<string, JsonSchemaProperty>;

  /** Nested object required fields */
  readonly required?: readonly string[];

  /** Union type (oneOf) */
  readonly oneOf?: readonly JsonSchemaProperty[];

  /** Union type (anyOf) */
  readonly anyOf?: readonly JsonSchemaProperty[];

  /** Numeric constraints */
  readonly minimum?: number;
  readonly maximum?: number;

  /** String constraints */
  readonly minLength?: number;
  readonly maxLength?: number;

  /** Array constraints */
  readonly minItems?: number;
  readonly maxItems?: number;

  /** String format (uuid, email, uri, etc.) */
  readonly format?: string;

  /** Default value */
  readonly default?: unknown;

  /** Whether additional properties are allowed (nested objects) */
  readonly additionalProperties?: boolean;
}

/**
 * Tool call from LLM
 */
export interface ToolCallRequest {
  readonly id: string;
  readonly name: string;
  readonly arguments: string; // JSON string
}

/**
 * Tool call response
 */
export interface ToolCallResponse {
  readonly id: string;
  readonly name: string;
  readonly result: ToolResult<unknown>;
}
